# Generated by Django 3.0.5 on 2020-04-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
