# Generated by Django 3.0.5 on 2020-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='blog\\static\x08log\\images\\logo.png', upload_to='static/images_article'),
        ),
    ]
