# Generated by Django 3.0.5 on 2020-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200416_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=None, upload_to='blog/static/blog/images_article'),
        ),
    ]
