# Generated by Django 3.0.5 on 2020-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200416_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=None, upload_to='blog/static/images_article'),
        ),
    ]
